import pandas as pd
import numpy as np
from imblearn.over_sampling import SMOTE
from ctgan import CTGAN
from sklearn.preprocessing import OneHotEncoder

RANDOM_SEED = 42

################################################################
# Adult income data processing
################################################################
def preprocess_adult(X):
    df = X.copy()

    # drop unhelpful columns
    df = df.drop(columns=["fnlwgt", "education"])

    # binary encode sex
    df["sex"] = (df["sex"] == "Male").astype(int)

    # OHE for nominal categoricals
    ohe_cols = ["workclass", "occupation", "native-country",
                "marital-status", "relationship", "race"]

    encoder = OneHotEncoder(sparse_output=False, handle_unknown="ignore")
    ohe_array = encoder.fit_transform(df[ohe_cols])
    ohe_df = pd.DataFrame(ohe_array, columns=encoder.get_feature_names_out(ohe_cols), index=df.index)

    # drop original cols and attach encoded ones
    df = df.drop(columns=ohe_cols)
    df = pd.concat([df, ohe_df], axis=1)

    return df, encoder

def preprocess_adult_encoder(X, encoder):
    df = X.copy()

    df = df.drop(columns=["fnlwgt", "education"])
    df["sex"] = (df["sex"] == "Male").astype(int)

    ohe_cols = ["workclass", "occupation", "native-country",
                "marital-status", "relationship", "race"]

    # transform only, no fit
    ohe_array = encoder.transform(df[ohe_cols])
    ohe_df = pd.DataFrame(ohe_array, columns=encoder.get_feature_names_out(ohe_cols), index=df.index)

    df = df.drop(columns=ohe_cols)
    df = pd.concat([df, ohe_df], axis=1)

    return df

def import_adult(path, num_skip_rows=0):
    """
    # skip_rows=1 for test data
    """
    col_names = [
    'age', 'workclass', 'fnlwgt', 'education', 'education-num',
    'marital-status', 'occupation', 'relationship', 'race', 'sex',
    'capital-gain', 'capital-loss', 'hours-per-week', 'native-country',
    'income']

    df = pd.read_csv(path, header=None, names=col_names,
                        skipinitialspace=True, skiprows=num_skip_rows)

    # Strip trailing '.' from income labels
    df['income'] = df['income'].str.rstrip('.')

    # Split features and target
    X = df.drop(columns=['income'])
    y = (df['income'] == '>50K').astype(int)

    return X, y

################################################################
# Default of Credit Card Clients data processing
################################################################
def import_credit(path):
    df = pd.read_csv(path, header=1, index_col=0)  # header=1 skips the X1/X2 row, index_col=0 drops ID

    X = df.drop(columns=['default payment next month'])
    y = df['default payment next month'].astype(int)

    return X, y

def import_credit_synthetic(path):
    df = pd.read_csv(path)
    X = df.drop(columns=['default.payment.next.month'])
    y = df['default.payment.next.month'].astype(int)
    return X, y

def preprocess_credit(X):
    df = X.copy()

    ohe_cols = ["SEX", "EDUCATION", "MARRIAGE"]

    encoder = OneHotEncoder(sparse_output=False, handle_unknown="ignore")
    ohe_array = encoder.fit_transform(df[ohe_cols])
    ohe_df = pd.DataFrame(ohe_array, columns=encoder.get_feature_names_out(ohe_cols), index=df.index)

    df = df.drop(columns=ohe_cols)
    df = pd.concat([df, ohe_df], axis=1)

    return df, encoder

def preprocess_credit_encoder(X, encoder):
    df = X.copy()

    ohe_cols = ["SEX", "EDUCATION", "MARRIAGE"]

    ohe_array = encoder.transform(df[ohe_cols])
    ohe_df = pd.DataFrame(ohe_array, columns=encoder.get_feature_names_out(ohe_cols), index=df.index)

    df = df.drop(columns=ohe_cols)
    df = pd.concat([df, ohe_df], axis=1)

    return df


################################################################
# Heart data ingest
################################################################
## Generated by claude code
def import_and_combine_heart(paths, impute=True):
    col_names = ['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs',
                 'restecg', 'thalach', 'exang', 'oldpeak', 'slope',
                 'ca', 'thal', 'target']

    dfs = []
    for path in paths:
        df = pd.read_csv(path, header=None, names=col_names, na_values='?')
        dfs.append(df)

    combined = pd.concat(dfs, ignore_index=True)
    combined['target'] = (combined['target'] > 0).astype(int)

    if impute:
        for col in ['trestbps', 'chol', 'thalach', 'oldpeak', 'ca']:
            combined[col] = combined[col].fillna(combined[col].median())
        for col in ['slope', 'thal', 'fbs', 'restecg', 'exang']:
            combined[col] = combined[col].fillna(combined[col].mode()[0])

    combined = combined.dropna().reset_index(drop=True)

    X = combined.drop(columns=['target'])
    y = combined['target']

    return X, y

def import_heart_synthetic(path):
    df = pd.read_csv(path, na_values='?')
    df = df.dropna().reset_index(drop=True)
    df['target'] = df['target'].astype(int)
    df['target'] = (df['target'] > 0).astype(int)
    X = df.drop(columns=['target'])
    y = df['target']
    return X, y

def preprocess_heart(X):
    df = X.copy()

    ohe_cols = ['cp', 'restecg', 'slope', 'thal']

    encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
    ohe_array = encoder.fit_transform(df[ohe_cols])
    ohe_df = pd.DataFrame(ohe_array, columns=encoder.get_feature_names_out(ohe_cols), index=df.index)

    df = df.drop(columns=ohe_cols)
    df = pd.concat([df, ohe_df], axis=1)

    return df, encoder


def preprocess_heart_encoder(X, encoder):
    df = X.copy()

    ohe_cols = ['cp', 'restecg', 'slope', 'thal']

    ohe_array = encoder.transform(df[ohe_cols])
    ohe_df = pd.DataFrame(ohe_array, columns=encoder.get_feature_names_out(ohe_cols), index=df.index)

    df = df.drop(columns=ohe_cols)
    df = pd.concat([df, ohe_df], axis=1)

    return df

################################################################
# Common functions used by all
################################################################
## Generated by claude
def sample_n_rows(X, y, n, seed=RANDOM_SEED):
    if n > len(X):
        print(f"Warning: requested {n} rows but only {len(X)} available, returning all rows")
    n = min(n, len(X))
    idx = (pd.Series(range(len(X))).sample(n=n, random_state=seed).index)
    X_sample = X.iloc[idx].reset_index(drop=True)
    y_sample = y.iloc[idx].reset_index(drop=True)
    return X_sample, y_sample

## Generated by claude
def combine_datasets(X1, y1, X2, y2, pct_from_1, seed=RANDOM_SEED):
    """
    Combine two datasets, sampling pct_from_1 (0.0-1.0) fraction from dataset 1
    and the remainder from dataset 2. Total size is min(len1/pct, len2/(1-pct))
    to avoid oversampling either source.
    """
    rng = np.random.default_rng(seed)

    # If percentage is given as a 0-100 integer, convert to decimal
    if pct_from_1 > 1:
        pct_from_1 = pct_from_1 / 100

    n_total = min(len(X1) / pct_from_1, len(X2) / (1 - pct_from_1))
    n1 = int(n_total * pct_from_1)
    n2 = int(n_total * (1 - pct_from_1))

    idx1 = rng.choice(len(X1), size=n1, replace=False)
    idx2 = rng.choice(len(X2), size=n2, replace=False)

    X_combined = pd.concat([X1.iloc[idx1], X2.iloc[idx2]], ignore_index=True)
    y_combined = pd.concat([y1.iloc[idx1], y2.iloc[idx2]], ignore_index=True)

    # Shuffle so dataset 1 and 2 samples aren't all bunched together
    shuffle_idx = rng.permutation(len(X_combined))
    return X_combined.iloc[shuffle_idx].reset_index(drop=True), \
           y_combined.iloc[shuffle_idx].reset_index(drop=True)

## Generated by Claude
def get_smote_data(X, y, n, seed=RANDOM_SEED):
    sm = SMOTE(random_state=seed)
    X_res, y_res = sm.fit_resample(X, y)

    X_synthetic = X_res.iloc[len(X):]
    y_synthetic = y_res.iloc[len(y):]

    # sample together before resetting index
    combined = X_synthetic.copy()
    combined['__target__'] = y_synthetic.values
    combined = combined.sample(n=n, random_state=seed).reset_index(drop=True)

    y_out = combined.pop('__target__')
    return combined, y_out

## Generated by Claude
def get_ctgan_data(X, y, n, discrete_columns=None, epochs=300):
    # smash X and y together since ctgan wants one dataframe
    target_col = y.name or "target"
    df = X.copy()
    df[target_col] = y.values

    # figure out which columns are categorical if we weren't told
    if discrete_columns is None:
        discrete_columns = list(
            df.select_dtypes(include=["object", "category"]).columns
        )

    # target should always be discrete (it's a class label)
    if target_col not in discrete_columns:
        discrete_columns.append(target_col)

    # train and generate
    model = CTGAN(epochs=epochs, verbose=True)
    model.fit(df, discrete_columns=discrete_columns)
    synthetic_df = model.sample(n)

    # split back out
    X_aug = synthetic_df.drop(columns=[target_col]).reset_index(drop=True)
    y_aug = synthetic_df[target_col].reset_index(drop=True)

    return X_aug, y_aug

def load_ctgan(path):
    df = pd.read_csv(path)
    y = df.pop('__target__')
    return df, y